#!/bin/bash
# AgentHQ Setup Script
# Called by the agent after collecting user preferences
# Usage: setup.sh <mode> [supabase_url] [supabase_key]
#   mode: "supabase" or "sqlite"

set -euo pipefail

AGENTHQ_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$AGENTHQ_DIR"

MODE="${1:-sqlite}"
SUPABASE_URL="${2:-}"
SUPABASE_KEY="${3:-}"
AUTH_SECRET=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p)

echo "Setting up AgentHQ in $MODE mode..."

# Generate .env.local
cat > .env.local << EOF
# AgentHQ Configuration
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Database mode: "supabase" or "sqlite"
DB_MODE=$MODE

# Auth
AUTH_PASSWORD=$(openssl rand -hex 8 2>/dev/null || head -c 16 /dev/urandom | xxd -p)
AUTH_SECRET=$AUTH_SECRET
EOF

if [ "$MODE" = "supabase" ]; then
  if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_KEY" ]; then
    echo "ERROR: Supabase mode requires URL and service key"
    exit 1
  fi
  cat >> .env.local << EOF

# Supabase
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_KEY=$SUPABASE_KEY
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_KEY=$SUPABASE_KEY
EOF
  echo "Supabase configured."
else
  mkdir -p data
  cat >> .env.local << EOF

# SQLite
SQLITE_PATH=./data/agenthq.db
EOF
  echo "SQLite configured at ./data/agenthq.db"
fi

# Install dependencies
echo "Installing dependencies..."
npm install 2>&1 | tail -3

# Build
echo "Building..."
npm run build 2>&1 | tail -5

AUTH_PW=$(grep AUTH_PASSWORD .env.local | cut -d= -f2)

# Set up observer cron (every 30s)
echo "Setting up observer cron..."
(command -v crontab &>/dev/null && crontab -l 2>/dev/null | grep -v "observer.py"; \
  echo "* * * * * cd $AGENTHQ_DIR && python3 observer.py >> observer.log 2>&1"; \
  echo "* * * * * sleep 30 && cd $AGENTHQ_DIR && python3 observer.py >> observer.log 2>&1") | command -v crontab &>/dev/null && crontab -
echo "Observer cron installed (every 30s)."

# Set up dispatcher (Supabase mode only)
if [ "$MODE" = "supabase" ]; then
  echo "Dispatcher available (Supabase mode)."
  echo "  Start: npx pm2 start python3 --name agenthq-dispatcher -- dispatcher.py"
  echo "  Env vars needed: SUPABASE_URL, SUPABASE_KEY, GATEWAY_URL (optional)"
fi

echo ""
echo "==============================="
echo " AgentHQ setup complete!"
echo "==============================="
echo ""
echo " Start:    npx pm2 start npm --name agenthq -- start"
echo " URL:      http://localhost:3000"
echo " Password: $AUTH_PW"
echo ""
echo " Observer: running every 30s (cron)"
if [ "$MODE" = "supabase" ]; then
echo " Dispatcher: npx pm2 start python3 --name agenthq-dispatcher -- dispatcher.py"
fi
echo ""
echo " To change password: edit AUTH_PASSWORD in .env.local"
echo ""
