#!/bin/bash
# AgentHQ Setup Script
# Called by the agent after collecting user preferences
# Usage: setup.sh <mode> [supabase_url] [supabase_key]
#   mode: "supabase" or "sqlite"

set -euo pipefail

AGENTHQ_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$AGENTHQ_DIR"

MODE="${1:-sqlite}"
SUPABASE_URL="${2:-}"
SUPABASE_KEY="${3:-}"
AUTH_SECRET=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p)

echo "Setting up AgentHQ in $MODE mode..."

# Generate .env.local
cat > .env.local << EOF
# AgentHQ Configuration
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Database mode: "supabase" or "sqlite"
DB_MODE=$MODE

# Auth
AUTH_PASSWORD=changeme
AUTH_SECRET=$AUTH_SECRET
EOF

if [ "$MODE" = "supabase" ]; then
  if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_KEY" ]; then
    echo "ERROR: Supabase mode requires URL and service key"
    exit 1
  fi
  cat >> .env.local << EOF

# Supabase
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_KEY=$SUPABASE_KEY
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_KEY=$SUPABASE_KEY
EOF
  echo "Supabase configured."
else
  mkdir -p data
  cat >> .env.local << EOF

# SQLite
SQLITE_PATH=./data/agenthq.db
EOF
  echo "SQLite configured at ./data/agenthq.db"
fi

# Install dependencies
echo "Installing dependencies..."
npm install --production 2>&1 | tail -3

# Build
echo "Building..."
npm run build 2>&1 | tail -5

echo ""
echo "Setup complete!"
echo "Start with: npx pm2 start npm --name agenthq -- start"
echo "Default password: changeme (change in .env.local)"
